services:
  mysql:
    image: mysql:8.0
    container_name: carbon-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: 66160114
      MYSQL_DATABASE: hotel_carbon_footprint

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/Dump20260902.sql:/docker-entrypoint-initdb.d/Dump20260902.sql:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: carbon-phpmyadmin
    restart: unless-stopped

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

    ports:
      - "8080:80"

    depends_on:
      - mysql

volumes:
  mysql_data: